const express = require('express')
const {SignUp, logIn, editPassword, editUserInfo, deleteAccount, sendOtp, changePassword, getUsers, getDay5Users, getDayBeforeDayBeforeYesterdaysUsers, getDayBeforeYesterdaysUsers, getYesterdaysUsers, getTodaysUsers } = require('../Controllers/Usercontroller')
const VerifyToken = require('../Middlewares/VerifyToken')
const Router = express.Router()


Router.post('/signup' , SignUp)
Router.post('/login' , logIn)
Router.post('/editPassword' , VerifyToken , editPassword)
Router.post('/editUserInfo' , VerifyToken , editUserInfo)
Router.post('/deleteUser' , VerifyToken , deleteAccount)
Router.post('/getOtp' ,  sendOtp)
Router.post('/changePassword' ,  changePassword)
Router.get('/getUsers' ,  getUsers)
Router.get('/getUsers1' , getTodaysUsers)
Router.get('/getUsers2' , getYesterdaysUsers)
Router.get('/getUsers3' , getDayBeforeYesterdaysUsers)
Router.get('/getUsers4' , getDayBeforeDayBeforeYesterdaysUsers)
Router.get('/getUsers5' , getDay5Users)
module.exports = Router